[phases.setup]
nixPkgs = ["php82", "php82Packages.composer", "mysql-client", "git", "unzip"]

[phases.install]
cmds = [
  "composer install --no-dev --optimize-autoloader --no-interaction --prefer-dist",
  "php artisan config:cache",
  "php artisan route:cache",
  "php artisan view:cache"
]

[phases.build]
cmds = [
  "php artisan migrate --force",
  "php artisan data:insert --force"
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"

[variables]
NODE_ENV = "production"

